FROM node:20-alpine
WORKDIR /app

# Copy file package.json & package-lock.json
COPY package.json package-lock.json ./

# Cài đặt dependencies
RUN npm install

# Copy toàn bộ mã nguồn
COPY . .

# Nếu bạn có script "start" trong package.json, nó thường là dev server
EXPOSE 3000
CMD ["npm", "start"]
