# Generated by Django 5.1.4 on 2025-03-05 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='constructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordercontractmappingbyconstructor',
            name='constructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed_constructor_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordercontractmappingbyconstructor',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constructor_contracts', to='orders.order'),
        ),
        migrations.AddField(
            model_name='ordercontractmappingbyuser',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_contracts', to='orders.order'),
        ),
        migrations.AddField(
            model_name='ordercontractmappingbyuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed_user_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderfile',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.order'),
        ),
        migrations.AddField(
            model_name='ourquotation',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_fee', to='category.category'),
        ),
        migrations.AddField(
            model_name='quotationinfo',
            name='constructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationfile',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.quotationinfo'),
        ),
        migrations.AddField(
            model_name='quotationordermapping',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_mappings', to='orders.order'),
        ),
        migrations.AddField(
            model_name='quotationordermapping',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_mappings', to='orders.quotationinfo'),
        ),
    ]
