# Generated by Django 5.1.4 on 2025-03-10 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfeedback',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='orders.order'),
        ),
    ]
