# Generated by Django 5.1.4 on 2025-03-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderfeedback_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='constructor_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='user_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
