# Generated by Django 5.1.7 on 2025-03-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_cointransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='incomeCoin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='outcomeCoin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='remainCoin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
