# Generated by Django 5.1.4 on 2025-03-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_cointransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourquotation',
            name='constructor_refund',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ourquotation',
            name='user_refund',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
