# Generated by Django 5.1.7 on 2025-03-30 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_incomecoin_order_outcomecoin_order_remaincoin'),
        ('orders', '0008_ourquotation_constructor_refund_and_more'),
    ]

    operations = [
    ]
