# Generated by Django 5.1.4 on 2025-03-12 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_constructor_confirmed_order_user_confirmed'),
        ('user', '0003_user_average_rating_user_completed_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='completed_orders',
        ),
        migrations.CreateModel(
            name='CompletedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_orders_as_constructor', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
