# Generated by Django 5.1.4 on 2025-03-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
