# Generated by Django 5.1.4 on 2025-03-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_orders_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
